export const LOAD_PHONEBOOK = 'LOAD_PHONEBOOK'
export const LOAD_PHONEBOOK_SUCCESS = 'LOAD_PHONEBOOK_SUCCESS'
export const LOAD_PHONEBOOK_FAILURE = 'LOAD_PHONEBOOK_FAILURE'

export const ADD_PHONEBOOK = 'ADD_PHONEBOOK'
export const ADD_DRAW_PHONEBOOK = 'ADD_DRAW_PHONEBOOK'  
export const ADD_PHONEBOOK_SUCCESS = 'ADD_PHONEBOOK_SUCCESS'
export const ADD_PHONEBOOK_FAILURE = 'ADD_PHONEBOOK_FAILURE'

export const REMOVE_PHONEBOOK = 'REMOVE_PHONEBOOK'
export const REMOVE_PHONEBOOK_SUCCESS = 'REMOVE_PHONEBOOK_SUCCESS'
export const REMOVE_PHONEBOOK_FAILURE = 'REMOVE_PHONEBOOK_FAILURE'

export const RESEND_PHONEBOOK = 'RESEND_PHONEBOOK'
export const RESEND_PHONEBOOK_SUCCESS = 'RESEND_PHONEBOOK_SUCCESS'
export const RESEND_PHONEBOOK_FAILURE = 'RESEND_PHONEBOOK_FAILURE'
export const RESEND_PHONEBOOK_CANCEL = 'RESEND_PHONEBOOK_FAILURE'

export const EDIT_PHONEBOOK = 'EDIT_PHONEBOOK'
export const EDIT_PHONEBOOK_SUCCESS = 'EDIT_PHONEBOOK_SUCCESS'
export const EDIT_PHONEBOOK_FAILURE = 'EDIT_PHONEBOOK_FAILURE'

export const SEARCH_PHONEBOOK = 'SEARCH_PHONEBOOK'
export const SEARCH_PHONEBOOK_SUCCESS = 'SEARCH_PHONEBOOK_SUCCESS'
export const SEARCH_PHONEBOOK_FAILURE = 'SEARCH_PHONEBOOK_FAILURE'